### ISSUE TITLE
INCOMPLETE View content button should show up when looking at details of a card that hasn't started yet

### ISSUE THREAD

**Issue by sheenarbw** [Umuzi-org/Tilde#467]
https://tilde-front-dot-umuzi-prod.nw.r.appspot.com/card/27868 

The button isn't showing up and it should.
Please make sure that when implementing this change you don't end up with duplicate buttons when looking at a card that has already started.

**Comment by sheenarbw** [comment]
Topic cards too please

**Comment by sheenarbw** [comment]
Changes reverted. There was a bug:

![Screenshot from 2022-06-24 12-34-27](https://user-images.githubusercontent.com/699166/175518474-036772a8-350a-4e36-bba5-6fb14e2d0340.png)

**Comment by Sbonelo01** [comment]
Thanks for this. My check was off. I should have checked for the start time instead of checking if it can be started. This PR https://github.com/Umuzi-org/Tilde/pull/530 should hopefully fix the bug.

Please see screenshots:

Backlog project card

![Screenshot_2022-06-24_13-21-26(backlog-project-no-duplicates)](https://user-images.githubusercontent.com/37469171/175524772-c3dcb5c0-1624-495b-9685-f2c57ecccbb5.png)

Backlog Topic card

![Screenshot_2022-06-24_13-20-40(back-log-no-duplicate)](https://user-images.githubusercontent.com/37469171/175524821-c5e4a1bc-63cb-456f-b73e-ba97b47068a7.png)

No duplicate on cards in the complete column

![Screenshot_2022-06-24_13-19-33(complete-card-no-duplicate)](https://user-images.githubusercontent.com/37469171/175524898-585b49d2-f14c-4c71-8206-1cc4d7322a20.png)

No duplicate for cards in review feedback:

![Screenshot_2022-06-24_13-18-24(review-feedback-no-duplicate)](https://user-images.githubusercontent.com/37469171/175525050-edc56c0d-3702-43fb-b859-8eefeec85ff3.png)

No duplicate for cards in review feedback

![Screenshot_2022-06-24_13-16-11(review-no-duplicate)](https://user-images.githubusercontent.com/37469171/175525136-38b8e11d-5469-435e-816f-058103be95c8.png)
